config/routes.rb
PersonalWebsite::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :messages, only: :create # Contact Me
  resources :songs, only: [:index, :new, :create]
  resources :articles, except: :destroy
  resources :categories, only: [:index, :new, :create] do
    resources :articles, only: [:index, :show]
  end
  resources :comments, only: [:index, :new, :create]
  resources :projects, only: [:index, :new, :create, :edit, :update]
  
  get "static_pages/home"

  root to: "static_pages#home"

end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: :slugged

  belongs_to :category
  has_many :comments

  attr_accessible :content, :summary, :title, :category_id, :picture

  validates :content, :summary, :title, presence: true
  validates :title, uniqueness: true
  validates_attachment_presence :picture

  has_attached_file :picture,
    storage: :dropbox,
    styles: { header: "770x400!" },
    dropbox_credentials: "#{Rails.root}/config/dropbox.yml"

  def self.search(search)
    if search
      where("title like ?", "%#{search}%")
    else
      order(:created_at)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :administrator, except: [:index, :show]
  before_filter :sidebar, only: [:index, :show]
  after_filter :count_visits, only: :show

  respond_to :json, :xml, only: [:show, :index] # Only for show and index actions

  def index
    if params[:search]
      @articles = Article.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 6)
    elsif params[:category_id].nil? or params[:category_id].empty?
      @articles = Article.order("created_at DESC").paginate(page: params[:page], per_page: 6)
    else
      @articles = Category.find(params[:category_id]).articles.order("created_at DESC").paginate(page: params[:page], per_page: 6)
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:success] = "#{@article.title} has been successfully created!"
      redirect_to @article
    else
      render "new"
    end
  end

  def show
    @article = Article.find(params[:id])
    @new_comment = Comment.new
    @comments = @article.comments.order("created_at DESC").paginate(page: params[:page], per_page: 20)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:success] = "#{@article.title} has been updated successfully!"
      redirect_to @article
    else
      render "edit"
    end
  end

  private
  def sidebar
    @selected_category = params[:category_id] ? Category.find(params[:category_id]).name : nil
    @categories = Category.order("name")
    @last_comments = Comment.order("created_at DESC").limit(10)
  end

  def count_visits
    @article.increment!(:visits)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<% if @articles.count.eql?(0) %>
  <div class="row-fluid">
    <div class="span12">
      <div class="alert alert-info">
        <h3>No articles were found</h3>
      </div>
    </div>
  </div>
<% else %>
  <% @articles.each do |article| %>
    <div class="row-fluid">
      <div class="span12">
        <h1><%= link_to article.title, article %></h1>
        <p>
          <i class="icon-calendar"></i> <%=   article.created_at.strftime("%d %b. %Y") %> | 
          <%= link_to article_path( article, anchor: "comments") do %>
            <i class="icon-comment"></i> <%= pluralize( article.comments.count, "comment") %>
          <% end %> | <i class="icon-group"></i> Visits: <%= article.visits %>
        </p>
        <div>
          <%= image_tag article.picture(:header) %>
        </div>
        <hr/>
        <p class="summary">
          <%= article.summary %>
        </p>
        <hr/>
        <div class="article-content">
          <%= truncate_html article.content, length: 500, omission: "...(continued)" %>
        </div>
        <div class="read-more" style="margin-top: 15px; margin-bottom: 15px; text-align: right;">
          <%= link_to article, class: "btn btn-success" do %>
            <i class="icon-eye-open"></i> Read More
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="control-group">
    <%= f.label :title, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :title, class: "input-block-level" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category, class: "control-label" %>
    <div class="controls">
      <%= f.collection_select(:category_id, Category.order("name"), :id, :name) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :picture, class: "control-label" %>
    <div class="control-group">
      <%= f.file_field :picture %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :summary, class: "control-label" %>
    <div class="controls">
      <%= f.text_area :summary, class: "input-block-level", rows: 3 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, class: "control-label" %>
    <div class="controls">
      <%= f.text_area :content, class: "input-block-level", rows: 15 %>
    </div>
  </div>
  <div class="controls">
    <%= f.submit "Create article", class: "btn btn-block btn-large btn-success" %>
  </div>
<% end %>

app/views/articles/_sidebar.html.erb
<div class="well">
  <ul class="nav nav-list">
    <li class="nav-header"><i class="icon-folder-open"></i> Categories</li>
    <% @categories.each do |category| %>
      <li><%= link_to category.name, category_articles_path(category) %></li>
    <% end %>
    <li class="nav-header"><i class="icon-bar-chart"></i> Popular Articles</li>
    <% @more_articles.each do |article| %>
      <li><%= link_to article.title, article %></li>
    <% end %>
  </ul>
</div>

app/views/articles/edit.html.erb
<h1>Edit: <%= @article.title %></h1>

<%= render "form" %>

app/views/articles/index.html.erb
<%= content_for :title, @selected_category ? @selected_category : "Articles" %>


<% if @selected_category %>
  <div class="row-fluid">
    <div class="span12">
      <ul class="breadcrumb">
        <li>
          <%= link_to root_path do %>
            <i class="icon-home"></i> Home
          <% end %>  
          <span class="divider">/</span>
        </li>
        <li><%= link_to "Articles", articles_path %> <span class="divider">/</span></li>
        <li class="active"><%= @selected_category %></li>
      </ul>
    </div>
  </div>
<% end %>

<div class="row-fluid">
  <div class="span8">
    <%= render "articles" %>
  </div>
  <div class="span4">
    <%= render "sidebar" %>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <div class="pagination pagination-centered">
      <%= will_paginate @articles, :renderer => BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<%= content_for :title, @article.title %>

<div class="row-fluid">
  <div class="span8">
    <h1><%= @article.title %></h1>
    <p>
      <i class="icon-calendar"></i> <%= @article.created_at.strftime("%d %b. %Y") %> | 
      <%= link_to article_path(@article, anchor: "comments") do %>
        <i class="icon-comment"></i> <%= pluralize(@article.comments.count, "comment") %>
      <% end %> | <i class="icon-group"></i> Visits: <%= @article.visits %>
    </p>
    <div>
      <%= image_tag @article.picture(:header) %>
    </div>
    <hr/>
    <p class="summary">
      <%= @article.summary %>
    </p>
    <hr/>
    <div class="article-content">
      <%= raw @article.content %>
    </div>
    <div>
      <div class="fb-like" data-send="true" data-width="450" data-show-faces="false"></div>
    </div>
    <hr id="comments"/>
    <div class="new-comment">
      <p class="lead">Add your comment:</p>
      <%= render "shared/new_comment" %>
      <div id="comment-bar" class="progress progress-striped progress-warning active" style="display: none;">
        <div class="bar" style="width: 100%;"></div>
      </div>
    </div>
    <div id="comments-wrapper">
      <%= render "shared/comments" %>
    </div>

    <div class="row-fluid">
      <div class="span12">
        <div class="pagination pagination-centered">
          <%= will_paginate @comments, :renderer => BootstrapPagination::Rails %>
        </div>
      </div>
    </div>
  </div>
  <div class="span4">
    <%= render "sidebar" %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $("#new-comment-btn").click(function(){
      $("#comment-bar").show();
    });
  });
</script>