config/routes.rb
PersonalWebsite::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :messages, only: :create # Contact Me
  resources :songs, only: [:index, :new, :create]
  resources :articles, except: :destroy
  resources :categories, only: [:index, :new, :create] do
    resources :articles, only: [:index, :show]
  end
  resources :comments, only: [:index, :new, :create]
  resources :projects, only: [:index, :new, :create, :edit, :update]
  
  get "static_pages/home"

  root to: "static_pages#home"

end

app/views/shared/_comments.html.erb
<% @comments.each_with_index do |comment, index| %>
  <div class="row-fluid">
    <div class="span12">
        <blockquote>
          <p>
            <%= image_tag comment.user.avatar_url, class: "user-avatar" %>
            <%= comment.content %>
          </p>
          <small><%= comment.user.name %> | <%= time_ago_in_words comment.created_at %> ago</small>
        </blockquote>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/shared/_new_comment.html.erb
<div class="row-fluid">
  <div class="span12">
    <% if user_signed_in? %>
      <%= form_for(@new_comment, url: comments_path, remote: true) do |f| %>
        <%= f.hidden_field :article_id, value: @article.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="control-group">
          <%= f.text_area :content, class: "span12", rows: 3, placeholder: "Type your comment here" %>
        </div>
        <div class="control-group">
          <%= f.submit "Post Comment", class: "btn btn-success", id:"new-comment-btn" %>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        To add a comment, sign in first.
      </div>
    <% end %>
  </div>
</div>