config/routes.rb
PersonalWebsite::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :messages, only: :create # Contact Me
  resources :songs, only: [:index, :new, :create]
  resources :articles, except: :destroy
  resources :categories, only: [:index, :new, :create] do
    resources :articles, only: [:index, :show]
  end
  resources :comments, only: [:index, :new, :create]
  resources :projects, only: [:index, :new, :create, :edit, :update]
  
  get "static_pages/home"

  root to: "static_pages#home"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :title, :picture, :url

  validates :title, :description, presence: true
  validates :title, uniqueness: true
  validates_attachment_presence :picture

  has_attached_file :picture,
    storage: :dropbox,
    styles: { main: "570x400!", thumbnail: "283x200!" },
    dropbox_credentials: "#{Rails.root}/config/dropbox.yml"

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!, except: :index

  respond_to :json, :xml, only: :index

  def index
    @projects  = Project.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:success] = "#{@project.title} has been created successfully!"
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find_by_id(params[:id])
  end

  def update
    @project = Project.find_by_id(params[:id])
    if @project.update_attributes(params[:project])
      flash[:success] = "#{@project.title} has been updated successfully!"
      redirect_to projects_path
    else
      render "edit"
    end
  end
  

end

app/views/projects/_form.html.erb
<div class="row-fluid">
  <div class="span12">
    <%= form_for @project do |f| %>
      <%= render "shared/error_messages", object: @project %>
      <div class="control-group">
        <%= f.label :title, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :title, class: "input-block-level" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :url, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :url , class: "input-block-level" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :picture, class: "control-label" %>
        <div class="controls">
          <%= f.file_field :picture %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :description, class: "control-label" %>
        <div class="controls">
          <%= f.text_area :description, class: "input-block-level", rows: 15 %>
        </div>
      </div>
      <div class="controls">
        <%= f.submit "Create Project", class: "btn btn-large btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= render "form" %>

app/views/projects/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <% @projects.each_with_index do |project, index| %>
      <% if index % 2 == 0 %>

        <div class="row-fluid">
          <div class="span3">
            <%= image_tag project.picture(:thumbnail) %>
            <p style="margin-top: 10px;">
              <% unless project.url.eql?("") %>
                <%= link_to "Visit project URL", project.url, class: "btn btn-block btn-success", target: "_blank" %>
              <% end %>
              <% if user_signed_in? and current_user.administrator %>
                <%= link_to "Edit project", edit_project_path(project), class: "btn btn-block btn-warning" %>
              <% end %>
            </p>
          </div>
          <div class="span9">
            <h4><%= project.title %></h4>
            <div><%= raw project.description %></div>
          </div>
        </div>
      
      <% else %>
      
        <div class="row-fluid">
          <div class="span9">
            <h4><%= project.title %></h4>
            <div><%= raw project.description %></div>
          </div>
          <div class="span3">
            <%= image_tag project.picture(:thumbnail) %>
            <p style="margin-top: 10px;">
              <% unless project.url.eql?("") %>
                <%= link_to "Visit project URL", project.url, class: "btn btn-block btn-success", target: "_blank" %>
              <% end %>
              <% if user_signed_in? and current_user.administrator %>
                <%= link_to "Edit project", edit_project_path(project), class: "btn btn-block btn-warning" %>
              <% end %>
            </p>
          </div>
        </div>
      
      <% end %>
      <hr/>
    <% end %>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <div class="pagination pagination-centered">
      <%= will_paginate @projects, :renderer => BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form" %>