config/routes.rb
PersonalWebsite::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :messages, only: :create # Contact Me
  resources :songs, only: [:index, :new, :create]
  resources :articles, except: :destroy
  resources :categories, only: [:index, :new, :create] do
    resources :articles, only: [:index, :show]
  end
  resources :comments, only: [:index, :new, :create]
  resources :projects, only: [:index, :new, :create, :edit, :update]
  
  get "static_pages/home"

  root to: "static_pages#home"

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39577149-1', 'jorgecoca.com');
  ga('send', 'pageview');
</script>

app/views/layouts/_contact_me.html.erb
<%= form_for(@contact_me_message) do |f| %>
  <%= render "shared/error_messages", object: @contact_me_message %>
  <div class="controls">
    <%= f.text_field :name, placeholder: "Your name", class: "span12" %>
  </div>
  <div class="controls">
    <%= f.text_field :email, placeholder: "Your email", class: "span12" %>
  </div>
  <div class="controls">
    <%= f.text_area :message, placeholder: "Message", class: "span12", rows: 11 %>
  </div>
  <div class="controls">
    <%= f.submit "Submit", class: "btn btn-success btn-large" %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row-fluid">
      <div class="span12">
        <h6 style="color: #ccc"><%= Time.now.year %> &#169; Jorge Coca | All rights reserved.</h6>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_instagram.html.erb
<ul class="thumbnails">
  <% @instagram_pictures.each_with_index do |picture, index| %>
    <li class="span4" <% if index % 3 == 0%>style="margin-left: 0px;"<% end %>>
      <a href="<%= picture[1] %>" class="thumbnail" target="_blank">
        <%= image_tag picture[0] %>
      </a>
    </li>
  <% end %>
</ul>

app/views/layouts/_technologies.html.erb
<ul id="technologies">
  <!-- <li><% image_tag "android-64.png", class: "android-tech" %></li> -->
  <li><%= image_tag "dropbox-64.png", class: "dropbox-tech" %></li>
  <!-- <li><% image_tag "apple-64.png", class: "apple-tech" %></li> -->
  <li><%= image_tag "github-64.png", class: "github-tech" %></li>
  <li><%= image_tag "facebook-64.png", class: "facebook-tech" %></li>
  <li><%= image_tag "instagram-64.png", class: "instagram-tech" %></li>
  <li><%= image_tag "twitter-64.png", class: "twitter-tech" %></li>
  <li><%= image_tag "rails-64.png", class: "rails-tech" %></li>
  <li><%= image_tag "heroku-64.png", class: "heroku-tech" %></li>
  <li><%= image_tag "spotify-64.png", class: "spotify-tech" %></li>
</ul>

app/views/layouts/_top_navbar.html.erb
<section id="top-section" class="navbar-fixed-top">
  <div class="container">
    <div class="row-fluid">
      <div class="span9">
        <div class="root-link">
          <%= link_to root_path, "data-toggle" => "tooltip", "data-placement" => "right", 
                        title: "Sometimes I pretend to be normal, but then it gets boring. So I go back and being me. =)" do %>
            <%= image_tag "jorge-coca.png" %>
            <span> Jorge Coca</span>
          <% end %>
        </div>
      </div>
      <div class="span3">
        <% if user_signed_in? %>
          <div class="logged-in-btn">
            <%= image_tag current_user.avatar_url, class: "img-circle user-avatar" %>
            <%= link_to "Log out #{current_user.name}", destroy_user_session_path, method: :delete, class: "btn btn-mini btn-danger" %>
          </div>
        <% else %>
          <a href="#sign-in-modal" class="btn btn-success btn-block sign-in-btn" data-toggle="modal">
            <i class="icon-white icon-user"></i> Sign In
          </a>
        <% end %>
      </div>
    </div>
  </div>
</section>

<div id="sign-in-modal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Sign in options</h3>
  </div>
  <div class="modal-body">
    <p>In order to comment on this website, you need first to log in using one of this methods:</p>
    <p>
      <%= link_to user_omniauth_authorize_path(:github), class: "btn btn-block btn-large" do %>
        <i class="icon-github"></i> Sign in with your Github account
      <% end %>
    </p>
    <p>
      <%= link_to user_omniauth_authorize_path(:facebook), class: "btn btn-block btn-large btn-primary" do %>
        <i class="icon-facebook"></i> Sign in with your Facebook account
      <% end %>
    </p>
    <p>
      <%= link_to user_omniauth_authorize_path(:twitter), class: "btn btn-block btn-large btn-inverse" do %>
        <i class="icon-twitter"></i> Sign in with your Twitter account
      <% end %>
    </p>
  </div>
  <div class="modal-footer">
    <%= link_to "Terms & Conditions", "#" %>
  </div>
</div>

app/views/layouts/_top_white_navbar.html.erb
<nav>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <ul class="nav pull-right social-links">
          <li>
            <a href="https://twitter.com/jcocaramos" target="_blank" data-toggle="tooltip" data-title="@jcocaramos">
              <i class="icon-twitter-sign icon-2x"></i>
            </a>
          </li>
          <li>
            <a href="https://github.com/jorgecoca" target="_blank" data-toggle="tooltip" data-title="jorgecoca">
              <i class="icon-github-sign icon-2x"></i>
            </a>
          </li>
          <li>
            <a href="http://www.linkedin.com/pub/jorge-coca-ramos/29/2b8/363/en" target="_blank" data-toggle="tooltip" title="Jorge Coca Ramos">
              <i class="icon-linkedin-sign icon-2x"></i>
            </a>
          </li>
        </ul>

        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="<%= 'active' if params[:action] == 'home' %>"><%= link_to "Home", root_path %></li>
            <li class="<%= 'active' if params[:controller] == 'articles' %>"><%= link_to "Articles", articles_path %></li>
            <li class="<%= 'active' if params[:controller] == 'projects' %>"><%= link_to "Projects", projects_path %></li>
            <li class="<%= 'active' if params[:controller] == 'songs' %>">
              <%= link_to "#song-of-the-day", "data-toggle" => "modal" do %>
                <i class="fc-webicon spotify small"></i> Song of the day
              <% end %>
            </li>
            <% if user_signed_in? and current_user.administrator %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Admin Menu <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "New Song", new_song_path %></li>
                  <li><%= link_to "New Category", new_category_path %></li>
                  <li><%= link_to "New Article", new_article_path %></li>
                  <li><%= link_to "New Project", new_project_path %></li>
                </ul>
              </li>
            <% end %>
          </ul>
          <ul class="nav pull-right">
            <li>
            <%= form_tag(articles_path, :method => "get", class: "navbar-form", id: "search-form") do %>
              <div class="input-append">
                <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Articles" %>
                <button class="btn" type="submit"><i class="icon-search"></i></button>
              </div>
            <% end %>
          </li>
          </ul>
        </div>

      </div>
    </div>
  </div>
</nav>

<!-- Modal Song of the day -->
<% unless @song_of_the_day.nil? %>
  <div id="song-of-the-day" class="modal hide fade">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3><%= @song_of_the_day.artist %> - <%= @song_of_the_day.title %></h3>
    </div>
    <div class="modal-body" style="text-align: center; max-height: 90px; overflow: hidden;">
      <%= spotify_player(@song_of_the_day.spotify_link) %>
    </div>
    <div class="modal-footer">
      <%= link_to "Visit my music collection", songs_path, class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/layouts/_white_footer.html.erb
<section id="white-footer">
  <div class="container">
    <div class="row-fluid" id="info-footer">
      <div class="span4" id="instagram-wrapper">
        <div class="title-divider">
          <h3>
            <style>.ig-b- { 
              display: inline-block; }
              .ig-b- img { visibility: hidden; }
              .ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
              .ig-b-v-24 { width: 137px; height: 24px; background: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24.png) no-repeat 0 0; }
                @media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
              .ig-b-v-24 { background-image: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24@2x.png); background-size: 160px 178px; } }
            </style>
            <a href="http://instagram.com/jcocaram?ref=badge" target="_blank" class="ig-b- ig-b-v-24">
              <img src="//badges.instagram.com/static/images/ig-badge-view-24.png" alt="Instagram" />
            </a>
          </h3>
        </div>
        <div class="row-fluid">
          <div class="span12">
            <%= render "layouts/instagram" %>
          </div>
        </div>
      </div>
      <div class="span4">
        <div class="title-divider">
          <h3><i class="icon-twitter"></i> Twitter</h3>
          <a class="twitter-timeline" href="https://twitter.com/jcocaramos" data-widget-id="312628047968866304">Tweets by @jcocaramos</a>
          <script>
            !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
          </script>
        </div>
      </div>
      <div class="span4">
        <div class="title-divider">
          <h3><i class="icon-user"></i> Contact Me</h3>
        </div>
        <div class="row-fluid">
          <div class="span12">
            <%= render "layouts/contact_me" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <%= render "layouts/technologies" %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jorge Coca | <%= content_for?(:title) ? yield(:title) : "Welcome to my personal website" %></title>
  <link rel="shortcut icon" href="/assets/favicon.png" type="image/png" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>
  <meta name="description" content="Software Engineer at Redpoint Techonologies, Chicago, United States. Enthusiastic of web technologies, 
  web services and mobile devices. RubyOnRails & PHP professional developer. Experienced programmer for iOS using ObjectiveC, and for Android using Java.">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : <%= ENV["FACEBOOK_APP_ID"] %>,                        // App ID from the app dashboard
      channelUrl : '//www.jorgecoca.com/channel.html', // Channel file for x-domain comms
      status     : true,                                 // Check Facebook Login status
      xfbml      : true                                  // Look for social plugins on the page
    });

    // Additional initialization code such as adding Event Listeners goes here
  };

  // Load the SDK asynchronously
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

  <%= render "layouts/top_navbar" %>

  <div class="container" id="wrapper">
    <%= render "layouts/top_white_navbar" %>
    <%= render "shared/flash_message" %>
    <div class="row-fluid">
      <div class="span12">
        <%= yield %>
      </div>
    </div>
  </div>
  <%= render "layouts/white_footer" %>
  <%= render "layouts/footer" %>
  <%= render "layouts/analytics" %>
</body>
</html>